### PR TITLE
Advertise generic_once_cell

### PR DESCRIPTION
**Pull request by mkroening**
I just published [generic_once_cell](https://crates.io/crates/generic_once_cell) (docs are still building).

This PR advertises generic_once_cell from the docs and the readme.

Closes https://github.com/matklad/once_cell/issues/207.

### CODE REVIEW

**Comment by mkroening** [comment]
Do you think the CI failure was sporadic, and we could try to merge again?

**Comment by matklad** [comment]
Ah, sorry missed the failure, seems spurious.

bors retry

**Comment by matklad** [comment]
nope, was a legit falure, should be fixed now, 

bors retry

**Pull request merged**
