### PR TITLE
chore: Update parking_lot to 0.8

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by matklad** [comment]
Thanks!

I wonder if bumping MSRV to 1.31 means that we should break the API to take advantage of new const-fns...

@mmstick you were interested in support for rustc 1.24. Do you still need it? 

I think what I am going to do is to simultaneously modernize the API, bump parking lot and bump MSRV. That way projects needing older rustc won't be broken by semver compatible update.

**Comment by mmstick** [comment]
I do not require 1.24 anymore. [Ubuntu 18.04 has been updated to ship rustc 1.31](https://packages.ubuntu.com/bionic/rustc)

**Comment by matklad** [comment]
CI is failing for MSRV, I'll merge manually as is and fix it up

**Comment by matklad** [comment]
Published 0.2.0

**Pull request merged**
