### PR TITLE
Test and bench synchronization

### PR DESCRIPTION
**Pull request by pitdicker**

### CODE REVIEW

**Comment by pitdicker** [comment]
Not sure what privileges I have with commit access, but lets give it a try! I think (hope) adding these two test is not really a problem.

bors r+

**Comment by matklad** [comment]
@pitdicker it looks like you haven't replied to the invitation email from GitHub (or I failed to properly invite you?). Re-sent the invite

**Comment by pitdicker** [comment]
I've got the mail now.
bors r+

**Comment by matklad** [comment]
I've manually synced reviewers, could you try again? :)

**Comment by pitdicker** [comment]
Thank you!

**Pull request merged**
