### PR TITLE
make once_cell::race::OnceBox available in alloc

### PR DESCRIPTION
**Pull request by xu-cheng**

### CODE REVIEW

**Comment by xu-cheng** [comment]
The CI failed on rust 1.31, whereas the alloc crate was stabilized in rust 1.36. 

Is there any suggestion to address this?

**Comment by xu-cheng** [comment]
```
  $ git push --tags --dry-run
  remote: Permission to matklad/once_cell.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/matklad/once_cell/': The requested URL returned error: 403
PUBLISH: 557.45ms
error: command `git push --tags --dry-run` failed, exit code: 128
```

This CI seems to be unrelated to my PR.

**Comment by matklad** [comment]
@xu-cheng could we change other usages of `std` to `alloc` in the same way?

>The CI failed on rust 1.31, whereas the alloc crate was stabilized in rust 1.36.

I'll bump MSRV to 1.36

>This CI error seems to be unrelated to my PR.

Yup, this shouldn't affect merge, though I wonder why `git tag --dry-run` does this...

**Comment by matklad** [comment]
Let's try to merge this though, and leave changes to std to a follow-up PR.

bors r+

**Comment by matklad** [comment]
>could we change other usages of std to alloc in the same way?

Ah, apparently we can't as that needs thread as well. Never mind then!

**Comment by matklad** [comment]
published as 1.5.1, thanks!

**Pull request merged**
